# -*- coding: utf-8 -*-
"""playing with pandas and streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uje4-pRQVRgzEdnHw3liDAVdG6MjR1ZN
"""

# This whole block goes in one Colab cell

# Import everything
import streamlit as st
import pandas as pd
import numpy as np

# Write your app code
st.set_page_config(page_title="My Easy App", layout="centered")
st.title("My Amazing Data App 📊")
st.write("This is so much easier!")

number = st.slider("Pick a number", 0, 100, 50)
st.write(f"You picked: {number}")

# Generate a sample chart
chart_data = pd.DataFrame(np.random.randn(20, 3), columns=["A", "B", "C"])
st.line_chart(chart_data)